article/urls.py
from django.urls import path

from article import views

app_name = 'article'

urlpatterns = [
    path('publish', views.publish, name='publish'),
    path('article_type/<int:type_id>', views.article_type, name='article_type'),
    path('leave', views.leave, name='leave'),
    path('article_info/<int:id>', views.article_info, name='article_info'),
    path('like_article', views.like_article, name='like_article'),
    path('del_article', views.del_article, name='del_article')
]

ormdemo/urls.py
from django.contrib import admin
from django.urls import path, include

from user.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    # 用户
    path('user/', include('user.urls', namespace='user')),
    # 文章
    path('article/', include('article.urls', namespace='article'))
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    # 注册
    path('register', views.register, name='register'),
    # 登录
    path('login', views.login, name='login'),
    # 账号激活
    path('user_active', views.user_active, name='user_active'),
    path('logout', views.logout, name='logout'),
    path('forget_code_pwd', views.forget_code_pwd, name='forget_code_pwd'),
    path('code_phone_pwd', views.send_phone_code, name='code_phone_pwd'),
    path('forget_mail_pwd', views.forget_mail_pwd, name='forget_mail_pwd'),
    path('code_mail_pwd', views.send_mail_code, name='code_mail_pwd'),
    path('center', views.center, name='center'),
    path('profile', views.profile, name='profile'),

    path('msg_center', views.msg_center, name='msg_center'),
    path('msg', views.msg, name='msg'),
    path('msg_update', views.msg_update, name='msg_update')
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <style>
        body {
            background-color: #efefef;
            height: 2000px;
        }

        * {
            margin: 0;
            padding: 0;
        }

        li {
            list-style: none;
        }

        .nav-box {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            height: 55px;
            background: rgba(255, 255, 255, .7);
            box-shadow: 0 2px 3px #999;
            z-index: 9;
        }

        .header-box {
            width: 980px;
            margin: 0 auto;
        }

        .content-box {
            width: 980px;
            margin: 70px auto 0;
            overflow: hidden;
            background-color: #bfa;
        }

        .logo {
            display: inline-block;
            width: 130px;
            height: 55px;
            text-align: center;
        }

        .logo a {
            font-size: 25px;
            line-height: 55px;
        }

        .right {
            float: right;
            height: 55px;
        }

        .nav > li {
            float: left;
            margin: 10px 5px;
        }

        .right li:hover {
            background-color: #eee;
        }

        .right li a {
            display: block;
            padding: 7px 22px
        }

        .text-color {
            color: #f65a85;
        }

        .icon-box {
            position: relative;
            top: 0;
            left: 0;
        }

        .icon-nav {
            position: absolute;
            top: 38px;
            left: -24px;
            width: 90px;
            padding: 3px 0;
            background-color: #eee;
            z-index: 9999;
        }

        .icon-nav li a {
            display: block;
            padding: 5px 5px 5px 15px;
            cursor: pointer;
        }

        .icon-box img {
            width: 30px;
            height: 30px;
            cursor: pointer;
        }
    </style>
    {% block style %}

    {% endblock %}
</head>
<body>
<div class="nav-box">
    <div class="header-box">
        <div class="logo">
            <a href="">晨曦记录</a>
        </div>
        <div class="right">
            <ul class="nav">
                <li><a href="{% url 'index' %}" class="text-color">首页</a></li>
                <li><a href="{% url 'article:article_type' type_id=1 %}">文章</a></li>
                <li><a href="{% url 'article:leave' %}">留言</a></li>
                {% if user %}
                    <li class="icon-box">
                        {% if user.userprofile.icon %}
                            <img src="/static/media/{{ user.userprofile.icon }}" alt="">
                        {% else %}
                            <img src="{% static 'media/new_icon.png' %}" alt="">
                        {% endif %}
                        <ul class="icon-nav" style="display: none">
                            <li><a href="{% url 'user:center' %}">我的主页</a></li>
                            <li><a href="{% url 'article:publish' %}">创作中心</a></li>
                            <li><a href="{% url 'user:msg_center' %}">消息</a></li>
                            <li><a href="">设置</a></li>
                            <li><a href="{% url 'user:logout' %}">退出</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'user:login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
<div class="content-box">
    {% block content %}
    {% endblock %}
</div>
<script>
    var flag = true
    $('.icon-box').click(function () {
        if (flag) {
            $('.icon-nav').css('display', 'block');
        } else {
            $('.icon-nav').css('display', 'none');
        }
        flag = !flag
    })

</script>
{% block js %}
{% endblock %}
</body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>服务器罢工了</h1>
</body>
</html>

templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物街</title>
</head>
<body>
<h2>{{ username }}：点击<a href="{{ path }}">激活</a>即可激活您的账号</h2>
<br>
<p>或者复制该链接去浏览器进行激活 {{ path }}</p>
</body>
</html>