article/urls.py
from django.urls import path

from article import views

app_name = 'article'

urlpatterns = [
    path('publish', views.publish, name='publish'),
    path('article_type/<int:type_id>', views.article_type, name='article_type'),
    path('leave', views.leave, name='leave'),
    path('article_info/<int:id>', views.article_info, name='article_info'),
    path('like_article', views.like_article, name='like_article'),
    path('del_article', views.del_article, name='del_article')
]

ormdemo/urls.py
from django.contrib import admin
from django.urls import path, include

from user.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    # 用户
    path('user/', include('user.urls', namespace='user')),
    # 文章
    path('article/', include('article.urls', namespace='article'))
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    # 注册
    path('register', views.register, name='register'),
    # 登录
    path('login', views.login, name='login'),
    # 账号激活
    path('user_active', views.user_active, name='user_active'),
    path('logout', views.logout, name='logout'),
    path('forget_code_pwd', views.forget_code_pwd, name='forget_code_pwd'),
    path('code_phone_pwd', views.send_phone_code, name='code_phone_pwd'),
    path('forget_mail_pwd', views.forget_mail_pwd, name='forget_mail_pwd'),
    path('code_mail_pwd', views.send_mail_code, name='code_mail_pwd'),
    path('center', views.center, name='center'),
    path('profile', views.profile, name='profile'),

    path('msg_center', views.msg_center, name='msg_center'),
    path('msg', views.msg, name='msg'),
    path('msg_update', views.msg_update, name='msg_update')
]

user/models.py
from django.db import models


# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=25, unique=True, null=False, blank=False)
    password = models.CharField(max_length=120, null=False, blank=False)
    create_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'user'


class UserProfile(models.Model):
    gender = models.BooleanField(default=0, null=True)
    phone = models.CharField(max_length=11, null=True)
    mail = models.CharField(max_length=50, null=True)
    icon = models.ImageField(upload_to='uploads/%Y/%m/%d/')
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'userprofile'


class Message(models.Model):
    send_id = models.IntegerField()
    receive_id = models.IntegerField()
    msg = models.TextField(null=False)
    is_delete = models.BooleanField(default=False)
    send_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'message'

user/views.py
import hashlib
import uuid

from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.template.loader import get_template
from django.urls import reverse

from article.models import Article
from ormdemo.settings import EMAIL_FROM
from user.models import User, UserProfile, Message

# 注册
from user.utils import Sample


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        mail = request.POST.get('mail')
        phone = request.POST.get('phone')
        confirm = request.POST.get('confirm')

        print(username, password, mail, phone, confirm)

        # 密码一致，进行加密，存储到数据库，发送激活邮件
        if password == confirm:
            password = hashlib.sha256(password.encode('utf8')).hexdigest()
            user = User.objects.create(username=username, password=password)
            UserProfile.objects.create(mail=mail, user_id=user.id, phone=phone)
            user.is_active = False
            user.save()

            # 生成 token 发送激活邮件
            token = str(uuid.uuid4()).replace('-', '')
            # 将生成的 token 和用户建立联系
            request.session[token] = user.id

            # 拼成激活链接
            path = 'http://100.100.6.186/user/user_active?token={}'.format(token)

            email_msg = get_template('mail.html').render({'username': username, 'path': path})
            send_mail(subject='激活邮件', message='', from_email=EMAIL_FROM, recipient_list=[mail], html_message=email_msg)

            return HttpResponse('账号激活邮件已发送，激活之后即可登录')
        else:
            return render(request, 'user/register.html', {'msg': '两次密码不一致！'})
    return render(request, 'user/register.html')


# 登录
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        rem_name = request.POST.get('rem_name')

        # 查找该用户
        user = User.objects.filter(username=username).first()
        # 判断 账号是否激活
        if not user.is_active:
            return HttpResponse('账号未激活')
        # 用户存在判断密码是否一致
        if user:
            password = hashlib.sha256(password.encode('utf8')).hexdigest()
            if user.password == password:
                # 使用session记录用户登录状态
                request.session['username'] = username

                # 登录 记住我
                response = redirect(reverse('index'))
                if rem_name == 'on':
                    response.set_cookie('username', user.username)
                return response
            else:
                return render(request, 'user/login.html', {'msg': '用户名或密码错误！'})
        else:
            return render(request, 'user/login.html', {'msg': '该用户还未注册！'})
    else:
        username = request.COOKIES.get('username', '')

    return render(request, 'user/login.html', {'username': username})


# 首页
def index(request):
    # 喜欢量
    articles = Article.objects.filter(is_delete=False).order_by('-like_num').all()
    articles = articles[:5]

    # 首页展示访问量最高的文章
    hots = Article.objects.filter(is_delete=False).order_by('-visit_num').all()
    hots = hots[:6]
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    return render(request, 'user/index.html', {'articles': articles, 'user': user, 'hots': hots})


# 邮箱激活
def user_active(request):
    token = request.GET.get('token')
    id = request.session.get(token)
    user = User.objects.get(pk=id)
    user.is_active = True
    user.save()
    request.session.pop(token)
    return redirect(reverse('user:login'))


# 退出登录
def logout(request):
    request.session.delete()
    # request.session.clear()  # 不删除数据库里的内容
    return redirect(reverse('index'))


# 忘记密码 手机号
def forget_code_pwd(request):
    if request.method == 'POST':
        phone = request.POST.get('phone')
        code = int(request.POST.get('code'))
        new_pwd = request.POST.get('new_pwd')
        session_code = request.session.get(phone)

        if session_code == code:
            new_password = hashlib.sha256(new_pwd.encode('utf8')).hexdigest()
            userprofile = UserProfile.objects.filter(phone=phone).first()
            userprofile.user.password = new_password
            userprofile.user.save()
            return render(request, 'user/login.html')
    return render(request, 'user/forget_code_pwd.html')


def send_phone_code(request):
    phone = request.GET.get('phone')
    if phone:
        import random
        # 生成随机验证码
        code = random.randint(100000, 999999)
        val = Sample.send(phone, code)

        if val.get('Code', '') == 'OK':
            request.session[phone] = code
            return JsonResponse({'msg': '发送成功'})

    return JsonResponse({'msg': '出错了'})


# 忘记密码 邮箱
def forget_mail_pwd(request):
    if request.method == 'POST':
        mail = request.POST.get('mail')
        code = int(request.POST.get('code'))
        new_pwd = request.POST.get('new_pwd')
        session_code = request.session.get(mail)

        if session_code == code:
            new_password = hashlib.sha256(new_pwd.encode('utf8')).hexdigest()
            userprofile = UserProfile.objects.filter(mail=mail).first()
            userprofile.user.password = new_password
            userprofile.user.save()
            return render(request, 'user/login.html')
    return render(request, 'user/forget_mail_pwd.html')


def send_mail_code(request):
    mail = request.GET.get('mail')
    if mail:
        import random
        # 生成随机验证码
        code = random.randint(100000, 999999)

        msg = '【晨曦记录】您的验证码%d，该验证码5分钟内有效，请勿泄露于他人！' % code

        val = send_mail('重置密码', msg, EMAIL_FROM, [mail])
        if val == 1:
            request.session[mail] = code
            return JsonResponse({'msg': '发送成功'})

    return JsonResponse({'msg': '出错了'})


# 个人中心
def center(request):
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    articles = user.article_set.filter(is_delete=False).all()
    return render(request, 'user/center.html', {'user': user, 'articles': articles})


def profile(request):
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    if request.method == 'POST':
        icon = request.FILES.get('icon')
        # username = request.POST.get('username')
        phone = request.POST.get('phone')

        user.userprofile.icon = icon
        # user.username = username
        user.userprofile.phone = phone
        user.save()
        user.userprofile.save()
        return HttpResponse('成功')
    return render(request, 'user/profile.html', {'user': user})


def msg_center(request):
    receive_id = int(request.GET.get('receive_id'))
    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    # print(receive_id, user.id)
    messages = Message.objects.filter(
        Q(send_id__in=[receive_id, user.id]) & Q(receive_id__in=[receive_id, user.id])).all()
    # print(messages)
    user1 = User.objects.get(pk=receive_id)
    return render(request, 'user/message_center.html',
                  {'receive_id': receive_id, 'user': user, 'user1': user1, 'messages': messages})


def msg(request):
    msg = request.POST.get('msg')
    send_id = request.POST.get('send_id')
    receive_id = request.POST.get('receive_id')

    Message(send_id=send_id, receive_id=receive_id, msg=msg).save()

    return JsonResponse({'msg': msg})


def msg_update(request):
    send_id = request.POST.get('send_id')
    receive_id = request.POST.get('receive_id')

    username = request.session.get('username')
    user = User.objects.filter(username=username).first()
    messages = Message.objects.filter(
        Q(send_id__in=[receive_id, user.id]) & Q(receive_id__in=[receive_id, user.id])).all()
    data = {'length': len(messages), 'data': []}
    for message in messages:

        data['data'].append({
            'send_username': User.objects.get(pk=message.send_id).username,
            'receive_username': User.objects.get(pk=message.receive_id).username,
            'msg': message.msg,
            'send_time': message.send_time
        })

    return JsonResponse(data)

templates/user/center.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    用户中心
{% endblock %}

{% block style %}
    <style>
        .header {
            position: relative;
            height: 240px;
            box-shadow: 1px 2px 3px #999;
            border-radius: 3px;
            overflow: hidden;
            margin-bottom: 15px;
        }

        .header .top {
            height: 140px;
            background-color: skyblue;
            overflow: hidden;
        }

        .header .top img {
            width: 100%;
        }

        .cover {
            position: absolute;
            top: 50px;
            right: 28px;
            padding: 5px 15px 5px 25px;
            border-radius: 3px;
            color: #d3d3d3;
            border: 1px solid #d3d3d3;
            cursor: pointer;
        }

        .head-icon {
            position: absolute;
            top: 48px;
            left: 24px;
            width: 168px;
            height: 168px;
            border: 5px solid #fff;
            border-radius: 5px;
        }

        .head-icon img {
            width: 100%;
            height: 100%;
        }

        .header .bottom {
            height: 100px;
            background-color: #fff;
            padding-top: 10px;
        }

        .edit {
            margin-left: 210px;
            overflow: hidden;
        }

        .edit span {
            display: block;
            font-size: 27px;
        }

        .edit a {
            float: right;
            margin-right: 30px;
            padding: 5px 15px;
            color: #06f;
            border-radius: 3px;
            border: 1px solid #06f;
        }

        .edit a:hover {
            background-color: rgba(0, 102, 255, .1);
        }

        .article-box {
            width: 100%;
            height: 180px;
            background-color: #fff;
            padding: 10px 20px 5px;
            margin-bottom: 10px;
            box-shadow: 1px 2px 3px #999;
        }

        .article-box a {
            text-decoration: underline;
        }

        .text {
            height: 86px;
        {#background-color: skyblue;#}

        }

        .text p {
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 3;
            overflow: hidden;
        }

        .icon {
            margin-top: 10px;
            font-size: 12px;
        }

        .right-nav {
            float: right;
            width: 238px;
            height: 500px;
            background-color: #bfa;
        }

        .left-article {
            float: left;
            width: 730px;
        }

        .about {
            height: 220px;
            margin-bottom: 20px;
            background: rgba(255, 255, 255, .5);
        }

        .about h2 {
            background-color: #fff;
            margin: 0;
            font-size: 18px;
            font-weight: 700;
            padding-left: 10px;
        }

        .count {
            width: 100%;
            height: 70px;
            padding: 10px;
            background-color: pink;
            margin-bottom: 20px;
            text-align: center;
        }

        .count span {
            display: inline-block;
            width: 49%;
        }

        .count span b {
            display: block;
        }

        .info a {
            margin-left: 20px;
            padding: 8px 50px;
            border: 1px solid #06f;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="header">
        <div class="top">
            <img src="{% static 'images/head.jpg' %}" alt="">
            <span class="cover">上传封面照片</span>
        </div>
        <div class="head-icon">
            {% if user.userprofile.icon %}
                <img src="/static/media/{{ user.userprofile.icon }}" alt="">
            {% else %}
                <img src="{% static 'media/new_icon.png' %}" alt="">
            {% endif %}
        </div>
        <div class="bottom">
            <div class="edit">
                <span>{{ user.username }}</span>
                <a href="{% url 'user:profile' %}">编辑个人资料</a>
            </div>
        </div>
    </div>
    <div class="middle">

        <div class="left-article">
            {% for article in articles %}
                <div class="article-box">
                    <div class="title">
                        <h4><a href="{% url 'article:article_info' article.id %}">{{ article.title }}</a></h4>
                    </div>
                    <div class="text">
                        <p>{{ article.text }}</p>
                    </div>
                    <div class="icon">
                        <span>作者：{{ article.user.username }}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <span>访问量：{{ article.visit_num }}</span>
                        <span>喜欢：{{ article.like_num }}</span>
                        <span>收藏：{{ article.save_num }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="right-nav">
            <div class="about">
                <h2>创作中心</h2>
                <div class="info-box">
                    <div class="info">
                        <div class="count">
                            <span>今日阅读数<b>0</b></span>
                            <span>今日点赞数<b>0</b></span>
                        </div>
                        <a href="{% url 'article:publish' %}">进入创作中心 ></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/forget_code_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}手机号修改密码{% endblock %}</title>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <style>
        body {
            background-color: #f1f1f1;
        }

        .box {
            width: 300px;
            height: 450px;
            background-color: #fff;
            margin: 80px auto;
            padding: 50px 50px 30px;
        }

        .content {
            width: 100%;
            height: 100%;
        }
    </style>
    {% block style %}
        <style>
            .nav {
                height: 50px;
                font-size: 20px;
                padding: 20px 0 0 70px;
            }

            .nav_style {
                color: #ea6f5a;
                border-bottom: 2px solid #ea6f5a;
            }

            .nav a {
                padding: 7px 15px;
            }

            .info {
                margin-top: 40px;
            }

            .info input {
                width: 250px;
                height: 42px;
                padding: 4px 12px 4px 35px;
                outline: none;
            }

            .btn {
                margin-top: 40px;
                width: 300px;
                height: 43px;
                border-radius: 21px;
                border: none;
                font-size: 18px;
                color: #fff;
                background-color: #42c02e;
                cursor: pointer;
            }
        </style>
    {% endblock %}
    {% block js %}{% endblock %}
</head>
<body>
<div class="box">
    {% if msg %}
        <div>{{ msg }}</div>
    {% endif %}
    <div class="content">
        {% block content %}
            <form action="{% url 'user:forget_code_pwd' %}" method="post">
                {% csrf_token %}
                <div class="nav">用手机号重置密码</div>
                <div class="info">
                    <div><input type="text" placeholder="手机号" name="phone"></div>
                    <div><input type="text" name="code" placeholder="验证码">
                        <button type="button" class="btn-code">发送验证码</button>
                    </div>
                    <div><input type="password" placeholder="新密码" name="new_pwd"></div>
                </div>
                <input type="submit" class="btn" value="修改密码">
            </form>
        {% endblock %}
    </div>
</div>
<script>
    $('.btn-code').click(function () {
        $(this).attr('disabled', true)
        let i = 59
        $(this).text(i + '后再次发送')
        let timer = setInterval(() => {
            $(this).text(--i + '后再次发送')
            if (i === 0) {
                clearInterval(timer)
                $(this).text('发送验证码')
                $(this).attr('disabled', false)
            }
        }, 1000)
        var phone = $('input[name="phone"]').val()
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
        $.getJSON('{% url 'user:code_phone_pwd' %}', {phone: phone, 'csrfmiddlewaretoken': csrf}, function (data) {
            console.log(data)
        })
    })
</script>
</body>
</html>

templates/user/forget_mail_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}手机号修改密码{% endblock %}</title>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <style>
        body {
            background-color: #f1f1f1;
        }

        .box {
            width: 300px;
            height: 450px;
            background-color: #fff;
            margin: 80px auto;
            padding: 50px 50px 30px;
        }

        .content {
            width: 100%;
            height: 100%;
        }
    </style>
    {% block style %}
        <style>
            .nav {
                height: 50px;
                font-size: 20px;
                padding: 20px 0 0 70px;
            }

            .nav_style {
                color: #ea6f5a;
                border-bottom: 2px solid #ea6f5a;
            }

            .nav a {
                padding: 7px 15px;
            }

            .info {
                margin-top: 40px;
            }

            .info input {
                width: 250px;
                height: 42px;
                padding: 4px 12px 4px 35px;
                outline: none;
            }

            .btn {
                margin-top: 40px;
                width: 300px;
                height: 43px;
                border-radius: 21px;
                border: none;
                font-size: 18px;
                color: #fff;
                background-color: #42c02e;
                cursor: pointer;
            }
        </style>
    {% endblock %}
    {% block js %}{% endblock %}
</head>
<body>
<div class="box">
    {% if msg %}
        <div>{{ msg }}</div>
    {% endif %}
    <div class="content">
        {% block content %}
            <form action="{% url 'user:forget_mail_pwd' %}" method="post">
                {% csrf_token %}
                <div class="nav">用邮箱重置密码</div>
                <div class="info">
                    <div>
                        <input type="text" placeholder="邮箱" name="mail">
                    </div>
                    <div>
                        <input type="text" name="code" placeholder="验证码">
                        <button type="button" class="btn-code">发送验证码</button>
                    </div>
                    <div>
                        <input type="password" placeholder="新密码" name="new_pwd">
                    </div>
                </div>
                <input type="submit" class="btn" value="修改密码">
            </form>
        {% endblock %}
    </div>
</div>
<script>
    $('.btn-code').click(function () {
        $(this).attr('disabled', true)
        let i = 59
        $(this).text(i + '后再次发送')
        let timer = setInterval(() => {
            $(this).text(--i + '后再次发送')
            if (i === 0) {
                clearInterval(timer)
                $(this).text('发送验证码')
                $(this).attr('disabled', false)
            }
        }, 1000)
        var mail = $('input[name="mail"]').val()
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
        $.getJSON('{% url 'user:code_mail_pwd' %}', {mail: mail, 'csrfmiddlewaretoken': csrf}, function (data) {
            console.log(data)
        })
    })
</script>
</body>
</html>

templates/user/index.html
{% extends 'base.html' %}
{% block title %}
    首页
{% endblock %}

{% block style %}
    <style>
        .middle {
            overflow: hidden;
        }

        .article-box {
            width: 100%;
            height: 180px;
            background-color: #fff;
            padding: 10px 20px 5px;
            margin-bottom: 10px;
            box-shadow: 1px 2px 3px #999;
        }

        .article-box a {
            text-decoration: underline;
        }

        .text {
            height: 86px;
        }

        .text p {
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 3;
            overflow: hidden;
        }

        .icon {
            margin-top: 10px;
            font-size: 12px;
        }

        .right-nav {
            float: right;
            width: 238px;
            height: 500px;
            background-color: #bfa;
        }

        .left-article {
            float: left;
            width: 730px;
        }

        .about {
            height: 210px;
            margin-bottom: 20px;
            background: rgba(255, 255, 255, .5);
        }

        .about h2 {
            background-color: #fff;
            margin: 0;
            font-size: 18px;
            font-weight: 600;
            padding: 10px 0 8px 15px;
        }

        .hot-box ul {
            padding: 10px 0 5px 15px;
        }

        .hot-box ul li {
            padding: 3px 0;
        }

        .search-box {
            border-bottom: 2px solid black;
        }

        .search-box input {
            text-indent: 10px;
            outline: none;
            height: 35px;
            border: none;
        }

        .search-box button {
            width: 58px;
            height: 35px;
            border: none;
            color: #fff;
            font-weight: 600;
            background-color: black;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="middle">
        <div class="left-article">
            {% for article in articles %}
                <div class="article-box">
                    <div class="title">
                        <h4><a href="{% url 'article:article_info' article.id %}">{{ article.title }}</a></h4>
                    </div>
                    <div class="text">
                        <p>{{ article.text }}</p>
                    </div>
                    <div class="icon">
                        <span>作者：{{ article.user.username }}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <span>访问量：{{ article.visit_num }}</span>
                        <span>喜欢：{{ article.like_num }}</span>
                        <span>收藏：{{ article.save_num }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="right-nav">
            <div class="about">
                <h2>热门</h2>
                <div class="hot-box">
                    <ul>
                        {% for hot in hots %}
                            <li><a href="{% url 'article:article_info' hot.id %}">{{ hot.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="search-box">
                <input type="text" name="search" placeholder="请输入关键字">
                <button>搜索</button>
            </div>
            <h4 style="margin-top: 30px;"><a href="http://100.100.1.36" style="color: red;">友情链接-柯</a></h4>
        </div>
    </div>
{% endblock %}

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}登录{% endblock %}</title>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <style>
        body {
            background-color: #f1f1f1;
        }

        * {
            margin: 0;
            padding: 0;
        }

        li {
            list-style: none;
        }

        .box {
            width: 300px;
            height: 370px;
            background-color: #fff;
            margin: 100px auto;
            padding: 50px 50px 30px;
        }

        .content {
            width: 100%;
            height: 100%;
        }
    </style>
    {% block style %}
        <style>
            .nav {
                height: 50px;
                font-size: 20px;
                padding: 20px 0 0 70px;
            }

            .nav_style {
                color: #ea6f5a;
                border-bottom: 2px solid #ea6f5a;
            }

            .nav a {
                padding: 7px 15px;
            }

            .info {
                margin-top: 40px;
                height: 110px;
            }

            .info input {
                width: 250px;
                height: 42px;
                padding: 4px 12px 4px 35px;
                outline: none;
            }

            .btn {
                margin-top: 40px;
                width: 300px;
                height: 43px;
                border-radius: 21px;
                border: none;
                font-size: 18px;
                color: #fff;
                background-color: #3194d0;
                cursor: pointer;
            }

            .s-left {
                float: left;
            }

            .s-right {
                float: right;
                cursor: pointer;
            }
        </style>
    {% endblock %}
    {% block js %}{% endblock %}
</head>
<body>
<div class="box">
    {% if msg %}
        <div>{{ msg }}</div>
    {% endif %}
    <div class="content">
        {% block content %}
            <form action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                <div class="nav">
                    <a class="login nav_style" href="{% url 'user:login' %}">登录</a>
                    <span>·</span>
                    <a class="register" href="{% url 'user:register' %}">注册</a>
                </div>
                <div class="info">
                    <div><input type="text" placeholder="用户名" name="username" value="{{ username }}"></div>
                    <div><input type="password" placeholder="密码" name="password"></div>
                </div>
                <div>
                    <div class="s-left">
                        <input type="checkbox" checked name="rem_name">记住我
                    </div>
                    <div class="s-right">
                        <span>登录遇到问题？</span>
                        <ul class="update-box" style="display: none">
                            <li><a href="{% url 'user:forget_code_pwd' %}">用手机号重置密码</a></li>
                            <li><a href="{% url 'user:forget_mail_pwd' %}">用邮箱重置密码</a></li>
                        </ul>
                    </div>
                </div>
                <input type="submit" class="btn" value="登录">
                <p style="text-align: center">----------其他社交账号----------</p>
            </form>
        {% endblock %}
    </div>
</div>

<script>
    var flag = true
    $('.s-right').click(function () {
        if (flag) {
            $('.update-box').css('display', 'block')
        } else {
            $('.update-box').css('display', 'none')
        }
        flag = !flag
    })
</script>
</body>
</html>

templates/user/profile.html
{% extends 'base.html' %}

{% block title %}
    编辑个人资料
{% endblock %}


{% block content %}
    <form action="{% url 'user:profile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>头像：<input type="file" name="icon"></p>
{#        <p>用户名：<input type="text" value="{{ user.username }}" name="username"></p>#}
{#        <p>性别： 男 <input type="radio" name="sex" value="1" {% if user.userprofile.gender == 1 %} checked {% endif %}> 女#}
{#            <input type="radio" name="sex" value="0" {% if user.userprofile.gender == 0 %} checked {% endif %}></p>#}
        <p>电话：<input type="text" value="{{ user.userprofile.phone }}" name="phone">
{#        </p>#}
        <p><input type="submit" value="修改"></p>
    </form>
{% endblock %}